
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: es-p3
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  # matchRegex: (?:kube|service)\.(.*)
  matchRegex: kube.var.log.containers.*_p3_.*-(\w|\.){68}$
  es:
    host: elasticsearch.escluster2.svc
    port: 9200
    generateID: true
    bufferSize: 20MB
    traceError: true
    logstashPrefix: p3-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"
    index: devops-applog-p3-%Y.%m.%d

# ---
# apiVersion: fluentbit.fluent.io/v1alpha2
# kind: ClusterOutput
# metadata:
#   name: containers-p3
#   labels:
#     fluentbit.fluent.io/infra: "true"
#     fluentbit.fluent.io/enabled: "true"
#     fluentbit.fluent.io/component: logging
# spec:
#   matchRegex: kube.var.log.containers.*_p3_.*-(\w|\.){68}$
#   es:
#     host: 172.16.100.10
#     index: devops-applog-p3-%Y.%m.%d
#     port: 9200
#     replaceDots: true
#     suppressTypeName: "false"
#     traceError: true
#     type: _doc
#     bufferSize: 10M
