# permissions for end users to edit clusterfluentdconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterfluentdconfig-editor-role
rules:
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusterfluentdconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusterfluentdconfigs/status
  verbs:
  - get
