# permissions for end users to view clusteroutputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusteroutput-viewer-role
rules:
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusteroutputs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusteroutputs/status
  verbs:
  - get
