# permissions for end users to view filters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filter-viewer-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  - fluentd.fluent.io
  resources:
  - filters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluentbit.fluent.io
  - fluentd.fluent.io
  resources:
  - filters/status
  verbs:
  - get
