# permissions for end users to edit fluentdconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentdconfig-editor-role
rules:
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentdconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentdconfigs/status
  verbs:
  - get
