# permissions for end users to edit fluentbitconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbitconfig-editor-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - fluentbitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - fluentbitconfigs/status
  verbs:
  - get
