# permissions for end users to view fluentds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-viewer-role
rules:
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds/status
  verbs:
  - get
