# permissions for end users to view outputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: output-viewer-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  - fluentd.fluent.io
  resources:
  - outputs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluentbit.fluent.io
  - fluentd.fluent.io
  resources:
  - outputs/status
  verbs:
  - get
