apiVersion: fluentbit.fluent.io/v1alpha2
kind: Input
metadata:
  name: input-sample
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  tail:
    tag: kube.*
    path: /var/log/containers/*.log
    parser: docker
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    skipLongLines: true
    db: /tail/pos.db
    dbSync: Normal
