apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
spec:
  service:
    parsersFile: parsers.conf
  inputSelector:
    matchLabels:
      http-output-demo: "true"
  filterSelector:
    matchLabels:
      http-output-demo: "true"
  outputSelector:
    matchLabels:
      http-output-demo: "true"
