apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: tail
  labels:
    http-output-demo: "true"
spec:
  tail:
    tag: kube.*
    path: /var/log/containers/log-generator_default_log-generator-*.log
    parser: docker
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    skipLongLines: true
    db: /tail/pos.db
    dbSync: Normal
