apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: http
  labels:
    http-output-demo: "true"
spec:
  match: kube.*
  http:
    host: "log-receiver"
    port: 8080
    format: "json"
#   uri: "/endpoint"
#   headers:
#     key1: value1
#     key2: value2

# -- Basic Auth --

#   httpUser:
#     valueFrom:
#       secretKeyRef:
#         name: log-receiver
#         key: usr
#   httpPassword:
#     valueFrom:
#       secretKeyRef:
#         name: log-receiver
#         key: pass

# ---- TLS ----
# Note that to use TLS files, you must append your secret to the list in `fluentbit.spec.secrets`.
# Read Path Convention for Secrets: https://github.com/kubesphere/fluentbit-operator#path-convention

#   tls:
#     caFile: "/fluent-bit/secrets/<secret_name>/<key_name>"
#     keyFile: "/fluent-bit/secrets/<secret_name>/<key_name>"
